[package]
name = "kraken_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
log = "0.4.5"
env_logger = "0.9.0"
serde = { version = "1.0.136", features = ["derive"] }